services:
  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ENVIRONMENT:development
      - FRAUD_SERVICE_ADDR=fraud:50052
      - VALIDATION_SERVICE_ADDR=validation:50053
      - METRICS_PORT=2114
      - OTLP_ENDPOINT=tempo:4318
    depends_on:
      - fraud
      - validation
      - tempo

  fraud:
    build:
      context: .
      dockerfile: docker/fraud.Dockerfile
    ports:
      - "50052:50052"
    environment:
      - METRICS_PORT=2112

  validation:
    build:
      context: .
      dockerfile: docker/validation.Dockerfile
    ports:
      - "50053:50053"
    environment:
      - METRICS_PORT=2113

  prometheus:
    image: prom/prometheus
    volumes:
      - ./pkg/logging/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./pkg/logging/tempo.yaml:/etc/tempo/tempo.yaml
    ports:
      - "4318:4318"
      - "3200:3200"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
