image:
  repository: gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

metrics:
  port: 2114

env:
  - name: SERVER_ENVIRONMENT
    value: "development"
  - name: FRAUD_SERVICE_ADDR
    value: "fraud:50052"
  - name: VALIDATION_SERVICE_ADDR
    value: "validation:50053"
  - name: METRICS_PORT
    value: "2114"
  - name: OTLP_ENDPOINT
    value: "tempo:4318"
