// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/proto/paymentpb/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_api_proto_paymentpb_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentpb_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentpb_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PaymentRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type FraudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFraudulent  bool                   `protobuf:"varint,1,opt,name=is_fraudulent,json=isFraudulent,proto3" json:"is_fraudulent,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudResponse) Reset() {
	*x = FraudResponse{}
	mi := &file_api_proto_paymentpb_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudResponse) ProtoMessage() {}

func (x *FraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentpb_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudResponse.ProtoReflect.Descriptor instead.
func (*FraudResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentpb_payment_proto_rawDescGZIP(), []int{1}
}

func (x *FraudResponse) GetIsFraudulent() bool {
	if x != nil {
		return x.IsFraudulent
	}
	return false
}

func (x *FraudResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	mi := &file_api_proto_paymentpb_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentpb_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentpb_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_paymentpb_payment_proto protoreflect.FileDescriptor

const file_api_proto_paymentpb_payment_proto_rawDesc = "" +
	"\n" +
	"!api/proto/paymentpb/payment.proto\x12\x05order\"l\n" +
	"\x0ePaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x04 \x01(\tR\breceiver\"N\n" +
	"\rFraudResponse\x12#\n" +
	"\ris_fraudulent\x18\x01 \x01(\bR\fisFraudulent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x12ValidationResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2I\n" +
	"\fFraudService\x129\n" +
	"\n" +
	"FraudCheck\x12\x15.order.PaymentRequest\x1a\x14.order.FraudResponse2X\n" +
	"\x11ValidationService\x12C\n" +
	"\x0fValidatePayment\x12\x15.order.PaymentRequest\x1a\x19.order.ValidationResponseB:Z8github.com/georgelopez7/grpc-project/api/proto/paymentpbb\x06proto3"

var (
	file_api_proto_paymentpb_payment_proto_rawDescOnce sync.Once
	file_api_proto_paymentpb_payment_proto_rawDescData []byte
)

func file_api_proto_paymentpb_payment_proto_rawDescGZIP() []byte {
	file_api_proto_paymentpb_payment_proto_rawDescOnce.Do(func() {
		file_api_proto_paymentpb_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_paymentpb_payment_proto_rawDesc), len(file_api_proto_paymentpb_payment_proto_rawDesc)))
	})
	return file_api_proto_paymentpb_payment_proto_rawDescData
}

var file_api_proto_paymentpb_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_paymentpb_payment_proto_goTypes = []any{
	(*PaymentRequest)(nil),     // 0: order.PaymentRequest
	(*FraudResponse)(nil),      // 1: order.FraudResponse
	(*ValidationResponse)(nil), // 2: order.ValidationResponse
}
var file_api_proto_paymentpb_payment_proto_depIdxs = []int32{
	0, // 0: order.FraudService.FraudCheck:input_type -> order.PaymentRequest
	0, // 1: order.ValidationService.ValidatePayment:input_type -> order.PaymentRequest
	1, // 2: order.FraudService.FraudCheck:output_type -> order.FraudResponse
	2, // 3: order.ValidationService.ValidatePayment:output_type -> order.ValidationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_paymentpb_payment_proto_init() }
func file_api_proto_paymentpb_payment_proto_init() {
	if File_api_proto_paymentpb_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_paymentpb_payment_proto_rawDesc), len(file_api_proto_paymentpb_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_paymentpb_payment_proto_goTypes,
		DependencyIndexes: file_api_proto_paymentpb_payment_proto_depIdxs,
		MessageInfos:      file_api_proto_paymentpb_payment_proto_msgTypes,
	}.Build()
	File_api_proto_paymentpb_payment_proto = out.File
	file_api_proto_paymentpb_payment_proto_goTypes = nil
	file_api_proto_paymentpb_payment_proto_depIdxs = nil
}
