global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fraud"
    static_configs:
      - targets: ["fraud:2112"]

  - job_name: "validation"
    static_configs:
      - targets: ["validation:2113"]

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:2114"]
